### ISSUE TITLE
Raise nicer Exception instead of calling sys.exit

### ISSUE THREAD

**Issue by DominicOram** [dials/nexgen#39]
As an external program using nexgen as a library (e.g. Artemis) it is unexpected that the library will call `sys.exit` if something goes wrong during file creation. Whilst `sys.exit` does raise an exception that I could deal with it isn't one I would normally expect from a library and so wouldn't necessarily guard against it.

**Comment by noemifrisina** [comment]
That makes a lot of sense. Probably not such a big issue in the command line tools, but at least in these instances:
```
nxs_write/NXclassWriters.py:137
nxs_write/__init__.py:96
beamlines/I24_Eiger_nxs.py:257
nxs_copy/CopyTristanNexus.py:205
```

**Comment by noemifrisina** [comment]
@DominicOram 
The sys.exit() in `nxs_copy/CopyTristanNexus.py:205` is in an obsolete function which will be removed before next release. The other 3 should have now been fixed (on `main`) if you'd like to take a quick look.

**Comment by DominicOram** [comment]
Reviewing changes in https://github.com/dials/nexgen/commit/e7c24ae87fafb9437e88e0a7f1c105078a0b304b:
* I don't think `SystemExit` is the best exception to throw. It inherits from `BaseException` rather than `Exception`, meaning that if Artemis did something like:
```python
try:
    nexgen_function()
except Exception:
    tell_gda_something_went_wrong() #<--- This is never called
```
In the best case Artemis would be able to do:
```python
try:
   nexgen_function()
except SpecificNexgenException:
   tell_gda_something_went_wrong()
```
There is some good general discussion on this in [here](https://betterprogramming.pub/a-comprehensive-guide-to-handling-exceptions-in-python-7175f0ce81f7), [here](https://realpython.com/the-most-diabolical-python-antipattern/) and in the official python [PEP8](https://peps.python.org/pep-0008/#programming-recommendations). The general best practice is for libraries to create their own `Exception` classes to specifically describe the problem but we could probably just use some of the in-built ones. I think instead for in `NXClassWriters` we should use a [ValueError](https://docs.python.org/3/library/exceptions.html#ValueError) for the one in `nxs_write/__init__.py` I'm not so sure, maybe `ValueError` again?
* If a function has the potential to raise an Exception it is normally mentioned in the docstrings e.g. search for `Raise` in this [example](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) 
* There are still a few `sys.exit()` calls left (https://github.com/dials/nexgen/search?q=sys.exit). I think we should change the one in `nexgen/__init__.py` as that is code that could be called from an outside module but the others are probably only used when called on the command line so not as bad
