### ISSUE TITLE
Allow writing VDS starting at non-zero index

### ISSUE THREAD

**Issue by DominicOram** [dials/nexgen#53]
For Artemis we have datasets that we want to split between multiple nexus files. e.g. If we're doing a 2 grid scans of `10*20` and `10*30` we would like to create two nexus files:
* `grid_scan_1.nxs` points to images `[0:201]`
* `grid_scan_2.nxs` points to images `[200:501]`

Currently `image_vds_writer` provides no way of writing the 2nd file. Note that this will also have to work when the images are spread over multiple `.h5` (e.g. when there are more than 1000)

**Comment by graeme-winter** [comment]
I have some tools for doing this for existing data which _do_ work -> 

https://github.com/graeme-winter/NXmxtools/blob/master/vdsmaker.py
